language: node_js

cache:
  yarn: true
  npm: true

node_js:
  - node

install:
  - yarn install

script:
  - yarn pack

deploy:
  provider: npm
  email: stephen.neal14@gmail.com
  api_key:
    secure: SNsBJK63oLEXgzbO/hYMjzAUmBAf+IA8xOB1yETN88PeIqbYyTmhhks0U53PA3wWabgytyDbx9dyOVED7AEaJ9u6X4Lw648udJ0hCoaDmtjwIUCBcLjjnXKq5BPCFLX3H+wA2MwD5jOARxhV2qqgwvdjbEtsYZo8U5c9Spo+NAiaYVT68iDm3EnBI845pK7gkRsWorOqHtJb4hgoDKl709SVwKZx1Oo6Ax3J0r4WVBw1wkE+Y/4muBM4xn9CaA/NXS9wFOlPo/PAqRi6s8c3RpA9/o1YeqtWZbbmqRF2sDb2kMe4KHwK+IOPbnRblszamJ7QQEJRS0D6kHtyLVMczaukQaCO5X1zgClck16yMokPx+5pIv3YO/GZUtUeiMgBLea9J1u37jUkojRCxfaA0uO+gz4083zSEwzgXuXoUvr+mHz/2fht4+hC5XB8rKeSvvt3spB6myjQXI98F1BI85eGIRs9WI/jB7bEorPPEui+IbZ1uN9/eSBcA7FdcnSyJvoPUgwYmO705IBcHDfhY/3iTb/l9bJx9rRP/Ne80qlN3vKjjTN2jiU2dGChy+E6Sv5TZuSQT1VO/W8G9Wp8HNPgcHfXwXYtHR5Z60DLPl4F2EkUs4jN1dNa+AAHkyQ2v2iE/88ug6BM1EhOKhucC3jQgYN+cbWupBbnO7WmyO4=
  skip_existing: true
  on:
    tags: true
    repo: sfneal/html-rivulet
  skip_cleanup: 'true'
